name: Status Checks

on:
  push:
    branches:
      - main
      - qa_test
  workflow_dispatch:       # <-- add this
    inputs:
      branch_name:         # optional input
        description: "Branch to run checks on"
        required: true

      - name: Custom Deployment Check
        run: echo "Ready for deployment"
